server:
  port : 8080
  shutdown : graceful
spring:
  cloud:
    config:
      enabled: false

backend:
  ryanair:
    api:
      base-url: https://services-api.abc.com
      read-timeout: 20000
      connect-timeout: 20000
      write-timeout: 20000
      max-in-memory-buffer-size-mb: 50
    endpoint:
      routes: /views/locate/3/routes
      schedules: /timtbl/3/schedules/{departure}/{arrival}/years/{year}/months/{month}

logging:
  level:
    org:
      springframework: INFO
      ryanair: TRACE

# Resilience4J properties
# #Enable circuit breaker health status
# Enable actuator health endpoints
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  # Retry
  retry:
    retryAspectOrder: 2
    instances:
      ryanair-api:
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        maxAttempts: 3
        waitDuration: 2s

  # Circuitbreaker
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      ryanair-api:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
